% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  brazilian,
  12pt,
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage[a4paper,left=3cm,right=2cm,top=3cm,bottom=2cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\ifLuaTeX
\usepackage[bidi=basic,shorthands=off]{babel}
\else
\usepackage[bidi=default,shorthands=off]{babel}
\fi
\ifLuaTeX
  \usepackage{selnolig} % disable illegal ligatures
\fi


\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


% Impede o sumário de colar na capa
\usepackage{tocloft}
\setcounter{tocdepth}{3}
\usepackage{placeins}
\usepackage{pdflscape}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\KOMAoption{captions}{tableheading}
\usepackage{xcolor}
\newcommand{\red}[1]{\textcolor{red}{#1}}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Índice}
\else
  \newcommand\contentsname{Índice}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{Lista de Figuras}
\else
  \newcommand\listfigurename{Lista de Figuras}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{Lista de Tabelas}
\else
  \newcommand\listtablename{Lista de Tabelas}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figura}
\else
  \newcommand\figurename{Figura}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Tabela}
\else
  \newcommand\tablename{Tabela}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listagem}
\newcommand*\listoflistings{\listof{codelisting}{Lista de Listagens}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdflang={pt-BR},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\author{}
\date{}
\begin{document}


\setstretch{1.5}
\begin{titlepage}
\centering

% --- IMAGEM NO TOPO ---
\includegraphics[width=0.3\textwidth]{figuras/logo_ufmg.jpg}

{\large UNIVERSIDADE FEDERAL DE MINAS GERAIS \par}
{\large Instituto de Ciências Exatas \par}
{\large Departamento de Ciência da Computação e Estatística \par}
{\large Pós-Graduação Lato Sensu em Ciência de Dados \par}

\vspace{2cm}

{\bfseries\Large Uma Análise Comparativa entre Inferência Frequentista e Bayesiana em Modelos de Regressão Aplicados à Aprovação de Empréstimos \par}

\vspace{2cm}

{\large Ana Beatriz Coelho Rodrigues \par}

\vfill

{\large Belo Horizonte \par}


{\large Ago/2026 \par}

\end{titlepage}

\newpage
\begin{center}

Ana Beatriz Coelho Rodrigues

\vspace{1cm}

{\bfseries\Large Uma Análise Comparativa entre Inferência Frequentista e Bayesiana em Modelos de Regressão Aplicados à Aprovação de Empréstimos}


\vspace{2cm}

\begin{flushright}
Monografia apresentada ao Curso de Especialização em Ciência de Dados com Ênfase em Estatística da Universidade Federal de Minas Gerais como requisito parcial para obtenção do grau de Especialista em Ciência de Dados.


\vspace{1cm}

Orientador(a): Prof.(a) Dr.(a) Fábio N. Demarqui~
\end{flushright}

\vfill

Belo Horizonte  

Ago/2026
\end{center}
\newpage

\newpage
\begin{center}
{\bfseries\Large RESUMO}
\end{center}

\vspace{1cm}

\textcolor{red}{reavaliar os resumos, quando o trabalho estiver concluído}

Este trabalho tem como objetivo comparar as abordagens de inferência frequentista e bayesiana no contexto de modelos de classificação aplicados à predição da aprovação de empréstimos bancários. O foco principal do estudo está na análise das diferenças conceituais, inferenciais e preditivas entre essas duas abordagens estatísticas, utilizando um conjunto de dados reais como estudo de caso para a aplicação dos modelos.

Inicialmente, são discutidos os fundamentos teóricos das abordagens frequentista e bayesiana, destacando suas principais características, pressupostos e formas de interpretação dos parâmetros. Em seguida, realiza-se uma análise exploratória dos dados com o objetivo de compreender a estrutura das variáveis e subsidiar a construção dos modelos, sem que a análise dos dados constitua o foco central do trabalho.

Na etapa de modelagem, são ajustados modelos de classificação sob as perspectivas frequentista e bayesiana, permitindo a comparação entre as abordagens quanto ao desempenho preditivo, à interpretação dos coeficientes estimados e à quantificação da incerteza associada às estimativas. A avaliação dos modelos é realizada por meio de métricas adequadas de classificação, possibilitando uma análise sistemática das diferenças e semelhanças entre os métodos.

Por fim, os resultados obtidos evidenciam as vantagens e limitações de cada abordagem no contexto de problemas de classificação binária, contribuindo para uma compreensão mais aprofundada das implicações práticas e metodológicas da escolha entre inferência frequentista e bayesiana em aplicações de análise de risco de crédito e ciência de dados.

\vspace{1cm}

\noindent\textbf{Palavras-chave:} regressão estatística; inferência frequentista; inferência bayesiana; modelos preditivos; análise de risco de crédito.
\newpage

\newpage
\begin{center}
{\bfseries\Large ABSTRACT}
\end{center}

\vspace{1cm}

This study aims to compare frequentist and Bayesian inference approaches in the context of regression models applied to the prediction of loan approval decisions. The main focus of the research lies in analyzing the conceptual, inferential, and predictive differences between these two statistical paradigms, using a real-world dataset as a case study for model application.

Initially, the theoretical foundations of frequentist and Bayesian approaches are discussed, highlighting their main characteristics, assumptions, and parameter interpretation frameworks. Subsequently, an exploratory analysis of the data is conducted in order to understand the structure of the variables and support model development, without making the data analysis itself the central focus of the study.

In the modeling stage, regression models are fitted under both frequentist and Bayesian perspectives, allowing for a comparative evaluation in terms of predictive performance, coefficient interpretation, and uncertainty quantification associated with the estimates. Model performance is assessed using appropriate classification metrics, enabling a systematic comparison between the two approaches.

Finally, the results highlight the strengths and limitations of each statistical approach in the context of binary classification problems, contributing to a deeper understanding of the practical and methodological implications of choosing between frequentist and Bayesian inference in credit risk analysis and data science applications.

\vspace{1cm}

\noindent\textbf{Keywords:} frequentist inference; Bayesian inference; regression models; predictive modeling; credit risk analysis.
\newpage

\tableofcontents
\newpage

\textbf{Legenda de status do documento}

\begin{itemize}
\tightlist
\item
  \textbf{{[}TBD{]}} → tópico ainda indefinido; estrutura ou escopo em
  discussão
\item
  \textbf{{[}TO DO{]}} → tópico planejado, ainda não iniciado
\item
  \textbf{{[}WIP{]}} → em desenvolvimento
\item
  \textbf{{[}DRAFT{]}} → versão preliminar do texto
\item
  \textbf{{[}CHECK{]}} → verificação pendente (conceitos, dados, código
  ou referências)
\item
  \textbf{{[}REVISÃO{]}} → versão completa, pronta para avaliação
\item
  \textbf{{[}AJUSTAR{]}} → ajustes finos de redação, figuras ou
  formatação (após revisão)
\item
  \textbf{{[}FINAL{]}} → versão definitiva (após revisão e ajustes
  finais)
\end{itemize}

\red{estou colocando comentários em vermelho para destacar pontos a revisar ou expandir}

\section{{[}TBD{]} Introdução}\label{tbd-introduuxe7uxe3o}

\begin{itemize}
\tightlist
\item
  Contexto de risco de crédito (motivação do trabalho)
\item
  Importância de modelos estatísticos na decisão financeira (com
  referencias de estudos anteriores)
\item
  Diferença conceitual entre abordagem frequentista e bayesiana
\item
  Motivação do estudo
\item
  Objetivo geral (resumida)
\item
  indicar as técnicas Estatísticas/Computacionais que serão utilizadas
  para a resolução do problema.
\item
  Estrutura do trabalho (Este trabalho está assim organizado: Na Seção 2
  apresentamos\ldots. A Seção 3 trata de\ldots{} )
\end{itemize}

\section{{[}TO DO{]} Referencial
Teórico}\label{to-do-referencial-teuxf3rico}

\red{um dos principais capítulos, já que o foco do trabalho é a comparação entre abordagens.}

\subsection{{[}TO DO{]} Fundamentos de Probabilidade e Inferência
Estatística}\label{to-do-fundamentos-de-probabilidade-e-inferuxeancia-estatuxedstica}

\begin{itemize}
\tightlist
\item
  Probabilidade como frequencia vs probabilidade como grau de crença
\item
  Variáveis aleatórias e distribuições
\item
  Teorema de Bayes
\item
  Conceito de incerteza estatística
\item
  Inferência como problema de estimação
\end{itemize}

\subsection{{[}TO DO{]} Problemas de Classificação em Aprendizado
Estatístico}\label{to-do-problemas-de-classificauxe7uxe3o-em-aprendizado-estatuxedstico}

\begin{itemize}
\tightlist
\item
  Classificação binária
\item
  Função de perda e decisão
\item
  Separabilidade linear e não linear
\item
  Overfitting e generalização (preparando terreno para problemas de
  crédito, onde a separação perfeita é improvável e o trade-off entre
  viés e variância é crucial)
\item
  Probabilidades preditas vs.~classes previstas
\item
  Threshold de decisão e custo de erro
\end{itemize}

\subsection{{[}TO DO{]} Avaliação de Modelos de
Classificação}\label{to-do-avaliauxe7uxe3o-de-modelos-de-classificauxe7uxe3o}

\begin{itemize}
\tightlist
\item
  Desbalanceamento de classes (muito comum em dados de crédito, mas não
  no dataset atual)
\item
  Matriz de confusão
\item
  Accuracy, Precision, Recall, F1-score
\item
  Curvas Precision--Recall
\item
  Curva ROC e AUC
\item
  Trade-off entre sensibilidade e especificidade
\item
  Custo assimétrico de erros (FP vs FN)
\end{itemize}

\subsection{{[}TO DO{]} Regressão Logística
Frequentista}\label{to-do-regressuxe3o-loguxedstica-frequentista}

\begin{itemize}
\tightlist
\item
  Formulação do modelo
\item
  Assumptions do modelo (e.g., independência, linearidade no logit,
  ausência de multicolinearidade)
\item
  Parametrização e interpretação
\item
  Interpretação dos coeficientes
\item
  Função logística
\item
  Estimação por máxima verossimilhança (e a função de verossimilhança)
\item
  Testes de hipótese
\item
  Intervalos de confiança
\item
  Odds e odds ratio
\item
  Limitações da abordagem frequentista
\end{itemize}

\subsection{{[}TO DO{]} Inferência
Bayesiana}\label{to-do-inferuxeancia-bayesiana}

\begin{itemize}
\tightlist
\item
  Teorema de Bayes aplicado à estatística
\item
  diferenças conceituais
\item
  parametros como variáveis aleatórias
\item
  Priors, likelihood e posterior
\item
  Incerteza e distribuição posterior
\item
  Vantagens da abordagem bayesiana
\item
  Atualização sequencial da evidência
\item
  Interpretação probabilística
\item
  controle de sobreajuste (\ldots)
  \red{Encaixar o que mais fizer sentido aqui.}
\end{itemize}

\subsection{{[}TO DO{]} Regressão Logística
Bayesiana}\label{to-do-regressuxe3o-loguxedstica-bayesiana}

\red{(sempre traçando paralelos com a versão frequentista)}

\begin{itemize}
\tightlist
\item
  Formulação do modelo probabilístico
\item
  Escolha de priors
\item
  Inferência via MCMC / aproximações variacionais
\item
  Diagnóstico de convergência (R-hat, traceplots)
\item
  Intervalos credíveis
\item
  Sensibilidade a priors
\item
  Robustez em pequenas amostras
\item
  Interpretação dos coeficientes sob posterior
\item
  Comparação direta de MLE e MAP MAP- Maximum-a-Posteriori MLE- maximum
  likelyhood estimation (\ldots)
  \red{Encaixar o que mais fizer sentido aqui.}
\end{itemize}

\subsection{{[}TO DO{]} Aplicações em Risco de Crédito e
Finanças}\label{to-do-aplicauxe7uxf5es-em-risco-de-cruxe9dito-e-finanuxe7as}

\red{Não estender muito, acho que 1 página já deve ser suficiente, o foco é a comparação}

(Contextualização)

\begin{itemize}
\item
  Modelos de scoring de crédito
\item
  Variáveis financeiras e risco
\item
  Decisão de concessão de empréstimos
\item
  Uso das probabilidades preditas para gestão de risco
\item
  Transparência e interpretabilidade
\item
  Em problemas de concessão de empréstimos, a incerteza é tão importante
  quanto a previsão.
\item
  O enfoque bayesiano permite incorporar conhecimento prévio do risco.
\item
  O enfoque frequentista fornece base tradicional de modelos de scoring.
\item
  A comparação entre ambas abordagens permite avaliar robustez das
  decisões.
\end{itemize}

\section{{[}WIP{]} Metodologia}\label{wip-metodologia}

\red{Aqui entra o dataset como aplicação, não como foco teórico.}

\subsection{{[}REVISÃO{]} Descrição dos
Dados}\label{revisuxe3o-descriuxe7uxe3o-dos-dados}

Os modelos desenvolvidos neste trabalho utilizam o Loan Approval
Dataset, uma base de dados pública disponibilizada na plataforma Kaggle
(Grewal (2026)). A variável alvo é binária, indicando o status de
aprovação do empréstimo. A Tabela~\ref{tbl-descricao} apresenta uma
descrição detalhada das variáveis presentes no conjunto de dados.

\begin{longtable}[]{@{}ll@{}}
\caption{Descrição das variáveis do
dataset}\label{tbl-descricao}\tabularnewline
\toprule\noalign{}
Feature & Descrição \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Feature & Descrição \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
No\_of\_dependents & Número de dependentes do solicitante \\
Education & Nível de escolaridade (Graduate / Not Graduate) \\
Self\_employed & Autônomo (Yes / No) \\
Income\_annum & Renda anual \\
Loan\_amount & Valor do empréstimo \\
Loan\_term & Prazo em anos \\
Cibil\_score & Score de crédito \\
Residential\_assets\_value & Bens residenciais \\
Commercial\_assets\_value & Bens comerciais \\
Luxury\_assets\_value & Bens de luxo \\
Bank\_asset\_value & Ativos bancários \\
Loan\_status & Variável alvo (Approved/Rejected) \\
\end{longtable}

Por se tratar de um dataset estruturado especificamente para fins de
aprendizado de máquina e análise estatística, ele oferece um cenário
controlado, permitindo focar na sensibilidade dos modelos aos preditores
e na quantificação da incerteza sem as inconsistências típicas de bases
de dados administrativas brutas.

\subsection{{[}TBD{]} Pré-processamento}\label{tbd-pruxe9-processamento}

\subsubsection{{[}REVISÃO{]} Verificação da Estrutura de dados e
tratamento de valores
ausentes}\label{revisuxe3o-verificauxe7uxe3o-da-estrutura-de-dados-e-tratamento-de-valores-ausentes}

Inicialmente, foi realizada a inspeção da estrutura do banco de dados,
com o objetivo de confirmar a consistência dos tipos das variáveis e a
adequação do formato dos dados às técnicas de modelagem adotadas. Essa
análise compreendeu a identificação das classes das variáveis, a
distinção entre atributos numéricos e categóricos e a validação da
variável resposta quanto à sua natureza e domínio.

A variável dependente, correspondente ao status do empréstimo, foi
confirmada como binária, atendendo às premissas dos modelos de regressão
logística. As variáveis explicativas foram classificadas conforme sua
natureza (contínua ou categórica), possibilitando a aplicação apropriada
de procedimentos de codificação e padronização quando necessário.

Por fim, a presença de valores ausentes foi avaliada por meio da função
is.na(), com sumarização via colSums(is.na()). Não foram identificadas
observações faltantes no conjunto de dados, eliminando a necessidade de
técnicas de imputação e evitando a introdução de incerteza adicional ou
viés sistemático no processo de estimação.

\subsubsection{{[}REVISÃO{]} Outliers}\label{revisuxe3o-outliers}

A identificação de valores atípicos (\texttt{outliers}) nas variáveis
numéricas foi realizada por meio do critério do intervalo interquartil
(\texttt{Interquartile\ Range}, IQR), amplamente utilizado em
estatística descritiva por sua robustez em relação a distribuições
assimétricas e à presença de valores extremos.

Para cada variável contínua, foram calculados o primeiro quartil \(Q_1\)
e o terceiro quartil \(Q_3\), definindo-se o intervalo interquartil como
\begin{equation}
\mathrm{IQR} = Q_3 - Q_1
\label{eq:iqr}
\end{equation}

Os limites inferior e superior para identificação de outliers são
definidos como

\begin{equation}
L = Q_1 - 1.5 \cdot \mathrm{IQR}
\label{eq:lower_bound}
\end{equation}

\begin{equation}
U = Q_3 + 1.5 \cdot \mathrm{IQR}
\label{eq:upper_bound}
\end{equation}

Esse procedimento foi empregado exclusivamente com finalidade
exploratória, visando caracterizar a distribuição das variáveis e
avaliar a presença de valores extremos potencialmente influentes. Não
foi realizada a exclusão automática de observações, de modo a preservar
a integridade do conjunto de dados e permitir que os modelos
estatísticos capturassem adequadamente a heterogeneidade inerente aos
dados financeiros.

O fator 1.5 no critério do IQR foi proposto por Tukey (1977) como um
compromisso empírico entre robustez e sensibilidade, sendo amplamente
adotado na literatura por sua boa performance em distribuições
assimétricas e com caudas longas, como é típico em dados financeiros.

No contexto de análise de risco de crédito, a presença de valores
extremos pode refletir perfis legítimos de alto patrimônio ou elevado
risco, sendo crucial que os modelos estatísticos sejam capazes de
acomodar essa variabilidade sem que a remoção indiscriminada de outliers
elimine informação relevante para a tarefa de classificação.

\subsubsection{{[}REVISÃO{]} Codificação de variáveis
categóricas}\label{revisuxe3o-codificauxe7uxe3o-de-variuxe1veis-categuxf3ricas}

Para viabilizar a inclusão de variáveis qualitativas nos modelos de
regressão, foi aplicada a técnica de One-Hot Encoding. Este procedimento
consiste na transformação de variáveis categóricas nominais em um
conjunto de variáveis indicadoras (binárias), onde o valor 1 representa
a presença da categoria e 0 a sua ausência.

Para a implementação, utilizou-se a função \texttt{dummy\_cols} do
pacote \texttt{fastDummies}, parametrizada com o argumento
\texttt{remove\_first\_dummy\ =\ TRUE}. Esta etapa é metodologicamente
crítica para mitigar a armadilha da variável dummy (multicolinearidade
perfeita), que ocorre quando as variáveis indicadoras são linearmente
dependentes, impossibilitando a estimação única dos parâmetros por
métodos de máxima verossimilhança ou por algoritmos de amostragem
bayesiana. Com a remoção da primeira categoria, o modelo estabelece uma
base de comparação necessária para a interpretação dos coeficientes
estimados.

\subsubsection{{[}TO DO{]} Padronização de variáveis
numéricas}\label{to-do-padronizauxe7uxe3o-de-variuxe1veis-numuxe9ricas}

Para assegurar a estabilidade numérica dos algoritmos de estimação e
permitir a comparabilidade entre os coeficientes do modelo, as variáveis
quantitativas foram submetidas ao processo de padronização
(Standardization). Inicialmente, realizou-se a coerção dos dados para o
tipo numérico e, em seguida, aplicou-se a transformação de escala
centralizada na média com unidade de desvio padrão. A fórmula utilizada
para a padronização de cada variável \(X\) é dada por
\begin{equation}
z_i = \frac{x_i - \mu}{\sigma}
\label{eq:standardization}
\end{equation}
onde \(x_i\) representa o valor original da variável, \(\mu\) é a média
amostral e \(\sigma\) é o desvio padrão amostral. Essa transformação
resulta em variáveis com média zero e desvio padrão um. Com todas as
variáveis na mesma escala, os coeficientes estimados tornam-se
comparáveis entre si, permitindo identificar quais preditores exercem
maior impacto relativo sobre a probabilidade de aprovação do empréstimo.

Na inferência frequentista, evita que variáveis com grandes magnitudes
(como Renda Anual) dominem a função de verossimilhança em detrimento de
variáveis com escalas menores. Na inferência bayesiana, facilita a
amostragem das distribuições posteriores pelos algoritmos de Cadeias de
Markov via Monte Carlo (MCMC), tornando a busca no espaço de parâmetros
mais eficiente.

\subsubsection{{[}TO DO{]} Estratégia de
Modelagem}\label{to-do-estratuxe9gia-de-modelagem}

\begin{itemize}
\tightlist
\item
  Separação treino/teste
\item
  Validação cruzada (se usar)
\item
  Métricas escolhidas
\end{itemize}

\paragraph{{[}REVISÃO{]} Divisão entre treino e
teste}\label{revisuxe3o-divisuxe3o-entre-treino-e-teste}

O conjunto de dados foi particionado em subconjuntos de treino (75\%) e
teste (25\%) por meio de amostragem aleatória estratificada em relação à
variável resposta Y=loan\_status. Essa estratégia assegura que as
distribuições marginais das classes sejam preservadas em ambos os
subconjuntos, como:
\begin{equation}
\mathbb{P}(Y = 1 \mid \text{treino})
\;\approx\;
\mathbb{P}(Y = 1 \mid \text{teste})
\;\approx\;
\mathbb{P}(Y = 1).
\label{eq:eq-treino-teste}
\end{equation}

A preservação das proporções de classe é fundamental em problemas de
classificação binária, pois evita distorções na estimação dos parâmetros
e na avaliação das funções de decisão, especialmente em cenários com
possíveis assimetrias entre as classes.

Os modelos foram estimados exclusivamente com observações do conjunto de
treino, enquanto o conjunto de teste foi utilizado apenas para a
avaliação do desempenho preditivo fora da amostra. Essa separação
garante que as métricas de desempenho estimadas correspondam a uma
aproximação não viesada do erro de generalização, reduzindo o risco de
sobreajuste (overfitting) e vazamento de informação.

\paragraph{Métricas de avaliação}\label{muxe9tricas-de-avaliauxe7uxe3o}

\subparagraph{Ajuste do modelo}\label{ajuste-do-modelo}

\begin{itemize}
\tightlist
\item
  Deviance
\item
  AIC
\item
  BIC
\item
  Teste da razão de verossimilhança
\end{itemize}

\subparagraph{Avaliação preditiva}\label{avaliauxe7uxe3o-preditiva}

A avaliação dos modelos de classificação foi realizada por meio de
métricas adequadas para problemas de classificação binária, considerando
a distribuição das classes e a importância relativa dos erros de
classificação. As métricas selecionadas incluem: - ROC-AUC (Área sob a
curva ROC) - Curva Precision-Recall e AUC-PR - Curva Sensibilidade
(Recall) e Especificidade - Matriz de confusão - Accuracy, Precision,
Recall e F1-score

\subsection{{[}TO DO{]} Modelos
Avaliados}\label{to-do-modelos-avaliados}

\begin{itemize}
\tightlist
\item
  Regressão logística frequentista
\item
  Regressão logística bayesiana (e deixa uma subseção ``Modelos
  adicionais'', caso queira)
\end{itemize}

\section{{[}WIP{]} Resultados}\label{wip-resultados}

\subsection{{[}REVISÃO{]} Análise
Exploratória}\label{revisuxe3o-anuxe1lise-exploratuxf3ria}

A análise exploratória tem como finalidade compreender a estrutura dos
dados, identificar padrões gerais, possíveis assimetrias, outliers e
relações preliminares entre variáveis. Essa etapa é fundamental para
orientar as decisões de modelagem, especialmente no que tange à escolha
de variáveis, tratamento de outliers e seleção de técnicas de modelagem
adequadas ao perfil dos dados.

O conjunto de dados é composto por 4269 observações e 13 variáveis,
incluindo a variável resposta \texttt{loan\_status}, que indica se o
empréstimo foi aprovado ou rejeitado. As variáveis preditoras incluem
informações como renda anual, pontuação de crédito
(\texttt{cibil\_score}), nível educacional, entre outras características
dos solicitantes.

\subsubsection{Estatísticas
univariadas}\label{estatuxedsticas-univariadas}

A Tabela~\ref{tbl-variaveis-num} apresenta as principais estatísticas
descritivas das variáveis numéricas do conjunto de dados, incluindo
média, mediana, valor mínimo e máximo. Em média, os solicitantes
apresentam aproximadamente 2 a 3 dependentes, renda anual em torno de 5
milhões e solicitam empréstimos próximos a 15 milhões. O prazo médio dos
empréstimos é de cerca de 11 anos, enquanto o score de crédito médio
está próximo de 600 pontos. Esses valores sugerem uma população com
perfil financeiro intermediário, mas com ampla variabilidade entre
indivíduos, com desvios-padrão elevados.

{

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-variaveis-num}Estatísticas descritivas das variáveis
numéricas do conjunto de dados.}

\tabularnewline

\toprule\noalign{}
& mean & median & min & max & std \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
no\_of\_dependents & 2.5 & 3 & 0 & 5 & 1.7 \\
income\_annum & 5.05912e+06 & 5.1e+06 & 200000 & 9.9e+06 &
2.80684e+06 \\
loan\_amount & 1.51335e+07 & 1.45e+07 & 300000 & 3.95e+07 &
9.04336e+06 \\
loan\_term & 10.9 & 10 & 2 & 20 & 5.71 \\
cibil\_score & 599.94 & 600 & 300 & 900 & 172.43 \\
residential\_assets\_value & 7.47262e+06 & 5.6e+06 & -100000 & 2.91e+07
& 6.50364e+06 \\
commercial\_assets\_value & 4.97316e+06 & 3.7e+06 & 0 & 1.94e+07 &
4.38897e+06 \\
luxury\_assets\_value & 1.51263e+07 & 1.46e+07 & 300000 & 3.92e+07 &
9.10375e+06 \\
bank\_asset\_value & 4.97669e+06 & 4.6e+06 & 0 & 1.47e+07 &
3.25019e+06 \\

\end{longtable}

}

A Tabela~\ref{tbl-categoricas} apresenta a distribuição das variáveis
categóricas do conjunto de dados. Observa-se que as categorias
analisadas exibem distribuições globalmente equilibradas, sem
predominância acentuada de um único grupo, o que contribui para a
estabilidade estatística e reduz potenciais vieses na etapa de
modelagem.

{

\begin{longtable}[]{@{}llrr@{}}

\caption{\label{tbl-categoricas}Distribuição das variáveis categóricas
do conjunto de dados.}

\tabularnewline

\toprule\noalign{}
variavel & categoria & n & percentual (\%) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
no\_of\_dependents & 0 & 712 & 16.68 \\
no\_of\_dependents & 1 & 697 & 16.33 \\
no\_of\_dependents & 2 & 708 & 16.58 \\
no\_of\_dependents & 3 & 727 & 17.03 \\
no\_of\_dependents & 4 & 752 & 17.62 \\
no\_of\_dependents & 5 & 673 & 15.76 \\
education & Graduate & 2144 & 50.22 \\
education & Not Graduate & 2125 & 49.78 \\
self\_employed & No & 2119 & 49.64 \\
self\_employed & Yes & 2150 & 50.36 \\

\end{longtable}

}

As variáveis financeiras apresentam elevada amplitude e distribuição
aproximadamente uniforme dentro de seus intervalos observados. Embora os
desvios-padrão sejam elevados em termos absolutos, a análise gráfica
feita na Figura~\ref{fig-distribuicoes} não indica forte assimetria ou
concentração modal acentuada.Esse comportamento sugere heterogeneidade
na amostra, mas com dispersão relativamente equilibrada ao longo do
espaço amostral.

Além disso, \texttt{cibil\_score} apresenta uma distribuição
relativamente mais concentrada em torno da mediana, o que sugere menor
variabilidade na avaliação de crédito em comparação com as variáveis
patrimoniais. Esse comportamento pode indicar que o score de crédito
atua como uma variável estabilizadora no processo de decisão de
concessão de empréstimos.

Outro ponto relevante é a presença de valores mínimos negativos em
\texttt{residential\_assets\_value}, o que pode indicar inconsistências
de registro ou tratamentos contábeis específicos no conjunto de dados.
Esse tipo de característica pode afetar a modelagem, exigindo atenção em
etapas de pré-processamento, especialmente em modelos sensíveis à escala
e à interpretação econômica das variáveis.

\begin{figure}

\begin{minipage}[t]{0.50\linewidth}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-1.pdf}

}

\subcaption{\label{fig-distribuicoes-1}Distribuição da renda anual}

\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-2.pdf}

}

\subcaption{\label{fig-distribuicoes-2}Distribuição do valor do
empréstimo}

\end{minipage}%
\newline
\begin{minipage}[t]{0.50\linewidth}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-3.pdf}

}

\subcaption{\label{fig-distribuicoes-3}Distribuição do prazo}

\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-4.pdf}

}

\subcaption{\label{fig-distribuicoes-4}Distribuição do CIBIL score}

\end{minipage}%
\newline
\begin{minipage}[t]{0.50\linewidth}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-5.pdf}

}

\subcaption{\label{fig-distribuicoes-5}Distribuição dos ativos
residenciais}

\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-6.pdf}

}

\subcaption{\label{fig-distribuicoes-6}Distribuição dos ativos
comerciais}

\end{minipage}%
\newline
\begin{minipage}[t]{0.50\linewidth}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-7.pdf}

}

\subcaption{\label{fig-distribuicoes-7}Distribuição dos bens de luxo}

\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-8.pdf}

}

\subcaption{\label{fig-distribuicoes-8}Distribuição dos ativos
bancários}

\end{minipage}%

\caption{\label{fig-distribuicoes}Distribuição das principais variáveis
numéricas do conjunto de dados}

\end{figure}%

\subsubsection{Análise da variável resposta e relações com as variáveis
preditoras}\label{anuxe1lise-da-variuxe1vel-resposta-e-relauxe7uxf5es-com-as-variuxe1veis-preditoras}

Na Figura~\ref{fig-target-plot}, observa-se a distribuição da variável
resposta \texttt{loan\_status}, indicando que aproximadamente 62.22\%
dos empréstimos foram aprovados, enquanto 37.78\% foram rejeitados. Essa
proporção sugere um desequilíbrio moderado na classe alvo, o que pode
influenciar a escolha de métricas de avaliação e estratégias de
modelagem.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{monografia_files/figure-pdf/fig-target-plot-1.pdf}}

}

\caption{\label{fig-target-plot}Distribuição da aprovação de
empréstimos}

\end{figure}%

A Figura~\ref{fig-distribuicoes-target} apresenta a estimativa de
densidade para as variáveis numéricas do conjunto de dados, segmentadas
pelo status de aprovação do empréstimo (Rejeitado ou Aprovado).
Observa-se que a variável \texttt{cibil\_score} é a que apresenta a
separação mais nítida entre as classes: candidatos com scores mais
baixos (aproximadamente abaixo de 600) concentram-se majoritariamente no
grupo de rejeitados, enquanto scores elevados mostram uma densidade
quase exclusiva de aprovações.

Em contraste, variáveis como \texttt{income\_annum} e os diferentes
tipos de ativos Figura~\ref{fig-distribuicoes-target} exibem
distribuições sobrepostas e visualmente semelhantes entre as duas
classes. Tal sobreposição indica que, isoladamente, essas variáveis
possuem menor poder discriminatório, o que exigirá dos modelos de
regressão a identificação de correlações mais complexas ou efeitos
multivariados para contribuir com a predição. No que tange ao
\texttt{loan\_term}, nota-se uma ligeira predominância de rejeições em
prazos muito curtos, enquanto os prazos mais longos apresentam uma
distribuição mais equilibrada entre os grupos.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{monografia_files/figure-pdf/fig-distribuicoes-target-1.pdf}}

}

\caption{\label{fig-distribuicoes-target}Distribuição das variáveis
numéricas por status de aprovação do empréstimo}

\end{figure}%

A Figura~\ref{fig-categoricas} apresenta a distribuição das frequências
absolutas para as variáveis categóricas Nível educacional, Trabalho
autônomo e Número de dependentes, segmentadas pelo status de aprovação.
Diferente do observado na variável cibil\_score, as variáveis
categóricas exibem uma distribuição notavelmente homogênea entre as
classes. Observa-se que a proporção entre empréstimos aprovados e
rejeitados mantém-se praticamente constante, independentemente de o
candidato ser graduado ou não, ou de possuir trabalho autônomo. No que
tange ao número de dependentes, o comportamento é análogo: não há uma
categoria específica (de 0 a 5 dependentes) que apresente uma vantagem
ou desvantagem desproporcional na aprovação do crédito. Sob a ótica da
modelagem estatística, essa independência aparente sugere que tais
variáveis podem apresentar coeficientes com menor magnitude ou maior
incerteza .

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{monografia_files/figure-pdf/fig-categoricas-1.pdf}}

}

\caption{\label{fig-categoricas}Distribuição das variáveis categóricas
segundo o status do empréstimo}

\end{figure}%

\subsubsection{Análise de correlação entre variáveis
numéricas}\label{anuxe1lise-de-correlauxe7uxe3o-entre-variuxe1veis-numuxe9ricas}

A matriz de correlação (Figura~\ref{fig-correlacao}) revela associações
relevantes entre as variáveis financeiras do conjunto de dados.
Observa-se forte correlação entre renda anual (\texttt{income\_annum}) e
valor do empréstimo (\texttt{loan\_amount}), bem como entre essas
variáveis e os ativos patrimoniais, especialmente ativos de luxo e
ativos bancários, indicando que essas medidas capturam aspectos
relacionados da condição financeira dos solicitantes. As correlações
entre os diferentes tipos de ativos são positivas e moderadas, sugerindo
coerência interna do perfil patrimonial, sem redundância perfeita entre
as variáveis.

Por outro lado, o prazo do empréstimo (\texttt{loan\_term}) apresenta
correlação praticamente nula com as demais variáveis, indicando
independência em relação ao perfil financeiro. De forma semelhante, o
cibil\_score exibe correlações muito fracas com renda, ativos e valor do
empréstimo, sugerindo que essa variável representa uma dimensão distinta
de risco de crédito, relevante para a classificação, mas não diretamente
associada ao nível de riqueza.

A presença de correlações elevadas entre algumas variáveis explicativas
indica potencial multicolinearidade, aspecto que deve ser considerado na
etapa de modelagem, especialmente na interpretação dos coeficientes da
regressão logística.

\begin{figure}[htbp]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{monografia_files/figure-pdf/fig-correlacao-1.pdf}}

}

\caption{\label{fig-correlacao}Mapa de calor da correlação entre
variáveis numéricas}

\end{figure}%

\subsubsection{Análise de outliers e
dispersão}\label{anuxe1lise-de-outliers-e-dispersuxe3o}

Complementarmente à análise de densidade, a
Figura~\ref{fig-boxplots-target} apresenta os boxplots das mesmas
variáveis, permitindo uma inspeção detalhada da dispersão, mediana e
presença de valores atípicos (outliers). É notável que, novamente, a
variável cibil\_score destaca-se por apresentar uma separação clara
entre as medianas dos grupos Rejeitado e Aprovado, com uma dispersão
significativamente menor nos aprovados, reforçando o observado na
Figura~\ref{fig-distribuicoes-target}. Essa característica sugere que o
cibil\_score é um preditor robusto e com alta capacidade discriminatória
para a classificação de risco de crédito.

Para as demais variáveis numéricas (como \texttt{loan\_amount},
\texttt{income\_annum} e os valores dos diferentes ativos) os boxplots
confirmam a semelhança entre as distribuições dos grupos, com medianas e
IQRs altamente sobrepostos. Essa característica reforça a hipótese de
que tais variáveis, por si sós, possuem baixo poder discriminatório para
a classificação. A identificação de valores atípicos, especialmente em
\texttt{residential\_assets\_value} e
\texttt{commercial\_assets\_value}, é um aspecto relevante para a
modelagem: enquanto a inferência frequentista pode exigir o tratamento
ou a robustez de estimadores frente a esses pontos, a abordagem
bayesiana oferece a vantagem de modelar a incerteza desses outliers
através de distribuições de cauda longa, permitindo uma avaliação mais
flexível do impacto desses casos nos parâmetros estimados.

A presença de valores atípicos, particularmente em variáveis
relacionadas a ativos patrimoniais, é corroborada quantitativamente pela
Tabela~\ref{tbl-outliers}, que apresenta o número e o percentual de
observações classificadas como outliers segundo o critério do intervalo
interquartil. Esses valores extremos refletem a heterogeneidade típica
de dados financeiros e possuem implicações diretas para a modelagem
estatística. Enquanto abordagens frequentistas podem demandar
procedimentos de tratamento ou estimadores robustos para mitigar a
influência desses pontos, modelos bayesianos permitem incorporar
explicitamente essa incerteza por meio de distribuições com caudas mais
pesadas, oferecendo maior flexibilidade na avaliação do impacto dos
outliers sobre os parâmetros estimados.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{monografia_files/figure-pdf/fig-boxplots-target-1.pdf}}

}

\caption{\label{fig-boxplots-target}Boxplots das variáveis numéricas por
status de aprovação do empréstimo}

\end{figure}%

{

\begin{longtable}[]{@{}lrr@{}}

\caption{\label{tbl-outliers}Número e percentual de outliers
identificados pelo critério do IQR}

\tabularnewline

\toprule\noalign{}
Feature & Outliers & Percentual \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
bank\_asset\_value & 5 & 0.0011712 \\
cibil\_score & 0 & 0.0000000 \\
commercial\_assets\_value & 37 & 0.0086671 \\
income\_annum & 0 & 0.0000000 \\
loan\_amount & 0 & 0.0000000 \\
loan\_term & 0 & 0.0000000 \\
luxury\_assets\_value & 0 & 0.0000000 \\
residential\_assets\_value & 52 & 0.0121808 \\

\end{longtable}

}

\subsection{{[}REVISÃO{]} Pré
processamento}\label{revisuxe3o-pruxe9-processamento}

\subsubsection{{[}REVISÃO{]} Verificação de valores ausentes e
duplicatas}\label{revisuxe3o-verificauxe7uxe3o-de-valores-ausentes-e-duplicatas}

Inicialmente, foi realizada a verificação da presença de valores
ausentes e observações duplicadas no conjunto de dados. Não foram
identificados missing values em nenhuma das variáveis, o que dispensou a
aplicação de técnicas de imputação e evitou a introdução de incerteza
adicional ou viés sistemático no processo de modelagem. Adicionalmente,
não foram detectadas observações duplicadas, assegurando que cada
registro corresponda a uma unidade amostral distinta e contribuindo para
a validade das estimativas inferenciais.

\subsubsection{{[}REVISÃO{]} Tratamento de inconsistências e
outliers}\label{revisuxe3o-tratamento-de-inconsistuxeancias-e-outliers}

Observa-se que aproximadamente 0.01\% dos solicitantes apresentam
valores negativos para ativos residenciais, correspondendo a um
contingente residual de observações atípicas. Esses valores não possuem
interpretação econômica direta no contexto da variável analisada e podem
estar associados a inconsistências de registro ou a particularidades não
representativas do perfil financeiro da amostra. Considerando o caráter
marginal dessas observações e seu potencial de introduzir ruído na
estimação dos parâmetros, optou-se por removê-las do conjunto de dados,
sem prejuízo à representatividade da amostra ou à validade inferencial
dos modelos ajustados. A exclusão resultou na remoção de 28 observações.

Não foi aplicado tratamento automático de outliers, uma vez que valores
extremos são esperados em dados financeiros e podem conter informação
relevante para a classificação do risco de crédito.

\subsubsection{{[}REVISÃO{]} Seleção de variáveis e análise de
correlação}\label{revisuxe3o-seleuxe7uxe3o-de-variuxe1veis-e-anuxe1lise-de-correlauxe7uxe3o}

A Figura~\ref{fig-correlacao} foi utilizada para investigar possíveis
relações de dependência linear entre as variáveis numéricas. Observou-se
a presença de correlações elevadas entre variáveis associadas à escala
de renda e patrimônio, como renda anual, valor do empréstimo e ativos
financeiros, comportamento esperado em bases de dados financeiras.

Apesar dessas correlações, optou-se por não remover variáveis nesta
etapa, uma vez que correlação elevada não implica, necessariamente,
multicolinearidade prejudicial à estimação, e tais variáveis podem
conter informação complementar relevante para a classificação do risco
de crédito.

\subsubsection{{[}REVISÃO{]} Codificação e padronização de
variáveis}\label{revisuxe3o-codificauxe7uxe3o-e-padronizauxe7uxe3o-de-variuxe1veis}

Com o objetivo de tornar os dados adequados à aplicação de modelos de
regressão logística, foi realizado um processo de codificação das
variáveis categóricas e padronização das variáveis numéricas. As
variáveis categóricas consideradas no estudo incluem: o nível
educacional (Graduate / Not Graduate) e a condição de trabalho autônomo
(Yes/No). Essas variáveis foram tratadas por meio de one-hot encoding,
convertendo cada categoria em variáveis indicadoras binárias. Para
evitar problemas de multicolinearidade perfeita, uma categoria de
referência foi removida em cada conjunto de dummies.

As variáveis numéricas foram padronizadas utilizando o método standard.
Essa etapa garante que todas as variáveis estejam na mesma escala,
facilitando a convergência dos algoritmos de estimação e permitindo uma
interpretação mais comparável dos coeficientes estimados.

Ressalta-se que a padronização não altera a informação contida nos
dados, mas apenas sua escala, sendo especialmente relevante em modelos
que utilizam métodos de otimização numérica e em abordagens bayesianas,
nas quais a escolha de distribuições a priori é sensível à magnitude dos
parâmetros.

\subsubsection{{[}REVISÃO{]} Separação
treino/teste}\label{revisuxe3o-separauxe7uxe3o-treinoteste}

O conjunto de dados foi dividido aleatoriamente em subconjuntos de
treino (75\%) e teste (25\%), utilizando amostragem estratificada em
relação à variável resposta (loan\_status). Essa estratégia assegura que
a proporção de observações pertencentes a cada classe seja preservada em
ambos os subconjuntos.

O ajuste do modelo foi realizado exclusivamente com o conjunto de
treino, enquanto o conjunto de teste foi reservado para a avaliação do
desempenho preditivo fora da amostra, assegurando a separação adequada
entre as etapas de estimação e validação.

\subsection{{[}WIP{]} Modelagem e
Avaliação}\label{wip-modelagem-e-avaliauxe7uxe3o}

\subsubsection{{[}WIP{]} Modelo
Frequentista}\label{wip-modelo-frequentista}

\begin{verbatim}

Call:
glm(formula = loan_status ~ ., family = binomial(link = "logit"), 
    data = treino)

Coefficients:
                         Estimate Std. Error z value Pr(>|z|)    
(Intercept)              -1.82901    0.13732 -13.319  < 2e-16 ***
no_of_dependents          0.07698    0.06896   1.116    0.264    
income_annum              1.72713    0.29252   5.904 3.54e-09 ***
loan_amount              -1.44130    0.19212  -7.502 6.27e-14 ***
loan_term                 0.89979    0.07540  11.934  < 2e-16 ***
cibil_score              -4.27739    0.16860 -25.369  < 2e-16 ***
residential_assets_value -0.01233    0.09019  -0.137    0.891    
commercial_assets_value  -0.04204    0.08831  -0.476    0.634    
luxury_assets_value      -0.18698    0.18309  -1.021    0.307    
bank_asset_value         -0.18645    0.12697  -1.468    0.142    
`education_Not Graduate`  0.06477    0.13790   0.470    0.639    
self_employed_Yes        -0.09346    0.13788  -0.678    0.498    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 4185.9  on 3180  degrees of freedom
Residual deviance: 1384.1  on 3169  degrees of freedom
AIC: 1408.1

Number of Fisher Scoring iterations: 7
\end{verbatim}

\paragraph{Avaliação do ajuste e propriedades estatísticas do
modelo}\label{avaliauxe7uxe3o-do-ajuste-e-propriedades-estatuxedsticas-do-modelo}

\begin{table}

\caption{\label{tbl-logit-freq-1}Estimativas do modelo de regressão
logística: coeficientes, odds ratios e intervalos de confiança de 95\%.}

\centering{

\caption{\label{tab:tbl-logit-freq-1}Estimativas do modelo de regressão logística.}
\centering
\begin{tabular}[t]{lrrrrrrr}
\toprule
Variável & Beta & StdErr & z & p-valor & OR & IC 95\% - & IC 95\% +\\
\midrule
(Intercept) & -1.83 & 0.14 & -13.32 & 0.00 & 0.16 & 0.12 & 0.21\\
no\_of\_dependents & 0.08 & 0.07 & 1.12 & 0.26 & 1.08 & 0.94 & 1.24\\
income\_annum & 1.73 & 0.29 & 5.90 & 0.00 & 5.62 & 3.18 & 10.03\\
loan\_amount & -1.44 & 0.19 & -7.50 & 0.00 & 0.24 & 0.16 & 0.34\\
loan\_term & 0.90 & 0.07 & 11.93 & 0.00 & 2.46 & 2.13 & 2.86\\
\addlinespace
cibil\_score & -4.28 & 0.17 & -25.37 & 0.00 & 0.01 & 0.01 & 0.02\\
residential\_assets\_value & -0.01 & 0.09 & -0.14 & 0.89 & 0.99 & 0.83 & 1.18\\
commercial\_assets\_value & -0.04 & 0.09 & -0.48 & 0.63 & 0.96 & 0.81 & 1.14\\
luxury\_assets\_value & -0.19 & 0.18 & -1.02 & 0.31 & 0.83 & 0.58 & 1.19\\
bank\_asset\_value & -0.19 & 0.13 & -1.47 & 0.14 & 0.83 & 0.65 & 1.06\\
\addlinespace
`education\_Not Graduate` & 0.06 & 0.14 & 0.47 & 0.64 & 1.07 & 0.81 & 1.40\\
self\_employed\_Yes & -0.09 & 0.14 & -0.68 & 0.50 & 0.91 & 0.70 & 1.19\\
\bottomrule
\end{tabular}

}

\end{table}%

O modelo de regressão logística foi estimado por máxima verossimilhança,
tendo como variável resposta o status do empréstimo e como variáveis
explicativas os atributos socioeconômicos e financeiros do solicitante.
A Tabela~\ref{tbl-logit-freq-1} apresenta as estimativas dos
coeficientes, erros-padrão, estatísticas z e respectivos valores-p.

O modelo apresentou redução substancial da deviance, passando de 4185.9
no modelo nulo para 1384.1 no modelo ajustado, com critério de
informação de Akaike (AIC) igual a 1408.1, indicando que a inclusão das
variáveis explicativas contribui significativamente para a explicação da
variável resposta. Adicionalmente, foi calculado o Critério de
Informação Bayesiano (BIC), cujo valor foi de 1480.9.

O BIC impõe uma penalização mais severa à complexidade do modelo do que
o AIC, sendo particularmente informativo em amostras de maior dimensão.
O valor obtido sugere que a especificação adotada mantém um equilíbrio
adequado entre qualidade de ajuste e parcimônia, reforçando a robustez
do modelo sob um critério mais conservador.

Entre as variáveis analisadas, income\_annum, loan\_amount, loan\_term e
cibil\_score mostraram-se estatisticamente significativas ao nível de
1\%. O coeficiente associado à renda anual (income\_annum) é positivo,
indicando que maiores níveis de renda aumentam a probabilidade de
aprovação do empréstimo, mantendo-se as demais variáveis constantes. Em
contrapartida, o valor solicitado (loan\_amount) apresenta coeficiente
negativo, sugerindo que empréstimos de maior montante estão associados a
uma menor probabilidade de aprovação, refletindo maior percepção de
risco por parte da instituição financeira.

O prazo do empréstimo (loan\_term) possui coeficiente positivo e
estatisticamente significativo, indicando que prazos mais longos tendem
a aumentar a chance de aprovação, possivelmente por reduzirem o valor
das parcelas e, consequentemente, o risco de inadimplência. A variável
cibil\_score destaca-se como o preditor mais relevante do modelo,
apresentando coeficiente negativo de grande magnitude e elevada
significância estatística. Esse resultado sugere forte associação entre
o score de crédito e a decisão de concessão, reforçando seu papel
central na avaliação de risco.

As demais variáveis, incluindo número de dependentes, valores de ativos
(residenciais, comerciais, de luxo e bancários), nível educacional e
status de trabalho autônomo, não apresentaram significância estatística
aos níveis usuais. Esse resultado sugere que, uma vez controladas as
variáveis centrais de renda, score de crédito, valor do empréstimo e
prazo, tais características adicionam informação marginal limitada para
a classificação do risco de crédito neste conjunto de dados.

O intercepto negativo e estatisticamente significativo reflete a
probabilidade basal de aprovação quando todas as variáveis explicativas
estão em seus valores de referência, reforçando a necessidade da
presença de características financeiras favoráveis para aumentar a
chance de concessão do crédito.

Como as variáveis quantitativas foram padronizadas, os coeficientes
estimados e seus respectivos Odds Ratios devem ser interpretados como o
efeito associado a um aumento de um desvio padrão na variável
explicativa, mantendo-se as demais constantes. Essa transformação
permite a comparabilidade direta da magnitude dos efeitos entre
variáveis originalmente medidas em escalas distintas. Portanto, um
aumento de um desvio padrão na renda anual está associado a um aumento
de 5.624 vezes na odds de aprovação do empréstimo, enquanto um aumento
de um desvio padrão no valor do empréstimo reduz as odds em 0.237 vezes,
e assim por diante para as demais variáveis.

O teste da razão de verossimilhança confirmou que o modelo ajustado
apresenta desempenho estatisticamente superior ao modelo sem covariáveis
(\(\chi^2 = 2801.8, \; df = 11, \; p < 0{,}001\)), evidenciando que o
conjunto de variáveis explicativas contribui de forma significativa para
a modelagem da probabilidade de aprovação do empréstimo.

\paragraph{Desempenho preditivo}\label{desempenho-preditivo}

\subparagraph{Avaliação do classificador a partir das probabilidades
estimadas}\label{avaliauxe7uxe3o-do-classificador-a-partir-das-probabilidades-estimadas}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{monografia_files/figure-pdf/fig-ROC-freq-1.pdf}}

}

\caption{\label{fig-ROC-freq}Curvas ROC para os conjuntos de treino e
teste}

\end{figure}%

A capacidade discriminatória do modelo foi avaliada por meio da Área sob
a Curva ROC (AUC), métrica amplamente utilizada em problemas de
classificação binária por ser independente da escolha de um limiar de
decisão e por avaliar diretamente a qualidade das probabilidades
estimadas.

A AUC pode ser interpretada como a probabilidade de que o modelo atribua
uma probabilidade maior a uma observação pertencente à classe positiva
do que a uma observação da classe negativa, escolhidas aleatoriamente.
Valores de AUC próximos de 1 indicam excelente poder discriminatório,
enquanto valores próximos de 0,5 sugerem desempenho equivalente ao
acaso.

Os resultados indicam AUC = 0.97 no conjunto de treino e AUC = 0.97 no
conjunto de teste. A proximidade entre esses valores sugere que o modelo
apresenta excelente capacidade de discriminação, mantendo desempenho
consistente fora da amostra utilizada para estimação dos parâmetros.

Além disso, a ausência de queda relevante da AUC do treino para o teste
indica baixo indício de sobreajuste (overfitting), reforçando a robustez
do modelo no que diz respeito à ordenação correta das probabilidades
preditas. Esse comportamento é particularmente relevante no contexto da
análise de risco de crédito, em que a correta hierarquização dos
indivíduos segundo o risco é mais importante do que decisões baseadas em
um único ponto de corte.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{monografia_files/figure-pdf/fig-PR-freq-1.pdf}}

}

\caption{\label{fig-PR-freq}Curvas Precision-Recall para os conjuntos de
treino e teste}

\end{figure}%

Complementarmente à análise por meio da curva ROC, avaliou-se o
desempenho do modelo utilizando a curva Precision--Recall (PR), a qual é
particularmente informativa em contextos de classes desbalanceadas ou
quando o interesse principal está na qualidade das previsões da classe
positiva.

Enquanto a curva ROC avalia a relação entre sensibilidade e
especificidade, a curva Precision--Recall enfatiza o compromisso entre
precisão (precision) --- a proporção de observações corretamente
classificadas como positivas entre todas as classificadas como positivas
--- e revocação (recall ou sensibilidade) --- a proporção de positivos
corretamente identificados. Dessa forma, a AUC--PR fornece uma medida
mais direta da utilidade prática das probabilidades estimadas quando o
custo de falsos positivos é relevante, como no contexto de concessão de
crédito.

A área sob a curva Precision--Recall foi calculada separadamente para os
conjuntos de treino e teste, resultando em AUC--PR = 0.94 no conjunto de
treino e AUC--PR = 0.951 no conjunto de teste. Esses valores elevados
indicam que o modelo apresenta alta capacidade de manter níveis
simultaneamente elevados de precisão e revocação, mesmo quando se exige
maior rigor na identificação da classe positiva.

De forma consistente com os resultados observados na curva ROC, a
similaridade entre as AUC--PR dos conjuntos de treino e teste sugere boa
capacidade de generalização e estabilidade do modelo fora da amostra de
estimação. Ademais, o desempenho superior na métrica Precision--Recall
reforça a adequação do modelo para aplicações em risco de crédito, nas
quais decisões baseadas em probabilidades bem calibradas são preferíveis
à simples classificação binária.

\begin{verbatim}
Setting levels: control = 0, case = 1
\end{verbatim}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{monografia_files/figure-pdf/fig-SE-freq-1.pdf}}

}

\caption{\label{fig-SE-freq}Curvas Sensibilidade-Especificidade em
função do limiar de decisão}

\end{figure}%

A escolha do limiar de corte da probabilidade foi baseada na análise
conjunta da sensibilidade e da especificidade do classificador, coomo
podemos ver na Figura~\ref{fig-SE-freq}. Para isso, foram avaliados os
valores dessas métricas ao longo de todo o intervalo de limiares
possíveis, construindo-se curvas de sensibilidade e especificidade em
função do limiar de decisão.

O ponto de corte ótimo foi definido a partir da maximização do índice de
Youden (Youden (1950)), que busca simultaneamente maximizar a taxa de
verdadeiros positivos e a taxa de verdadeiros negativos. Esse critério
fornece um equilíbrio entre erros de classificação dos dois tipos,
evitando a adoção arbitrária do valor padrão de 0,5.

O limiar selecionado (0.275) foi então utilizado para a construção da
matriz de confusão e para o cálculo das métricas de desempenho no
conjunto de teste.

\subparagraph{Avaliação do desempenho classificatório sob limiar de
decisão}\label{avaliauxe7uxe3o-do-desempenho-classificatuxf3rio-sob-limiar-de-decisuxe3o}

{

\begin{longtable}[]{@{}lrr@{}}

\caption{\label{tbl-confusao-treino-freq}Matriz de confusão do modelo de
regressão logística (conjunto de treino)}

\tabularnewline

\toprule\noalign{}
& 0 & 1 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 1756 & 35 \\
1 & 254 & 1136 \\

\end{longtable}

}

{

\begin{longtable}[]{@{}lrr@{}}

\caption{\label{tbl-confusao-teste-freq}Matriz de confusão do modelo de
regressão logística (conjunto de teste)}

\tabularnewline

\toprule\noalign{}
& 0 & 1 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 555 & 15 \\
1 & 75 & 415 \\

\end{longtable}

}

\begin{table}
\caption{Métricas de desempenho do modelo de regressão logística para os
conjuntos de treino e teste}\tabularnewline

\centering
\begin{tabular}{lrrrrrrr}
\toprule
Conjunto & Accuracy & Precision & Recall & Specificity & F1 & AUC\_ROC & AUC\_PR\\
\midrule
Treino & 0.91 & 0.82 & 0.97 & 0.87 & 0.89 & 0.97 & 0.94\\
Teste & 0.92 & 0.85 & 0.97 & 0.88 & 0.90 & 0.97 & 0.95\\
\bottomrule
\end{tabular}
\end{table}

Após a definição do limiar de decisão, as previsões probabilísticas
foram convertidas em classes, permitindo a construção das matrizes de
confusão para os conjuntos de treino e teste (Tabelas
Tabela~\ref{tbl-confusao-treino-freq} e
Tabela~\ref{tbl-confusao-teste-freq}).

A partir dessas matrizes, foram calculadas métricas clássicas de
desempenho, incluindo acurácia, precisão, sensibilidade, especificidade
e F1-score, cujos valores estão sumarizados na
(\textbf{metricas-freq?}).

Adicionalmente, métricas independentes do limiar de decisão, como
AUC-ROC e AUC-PR, foram reportadas para avaliar a qualidade global das
probabilidades estimadas.

\begin{itemize}
\tightlist
\item
  Análise de Sensibilidade à Multicolinearidade (já que temos features
  com correlação elevada)
\end{itemize}

\subsubsection{{[}TBD{]} Modelo Bayesiano}\label{tbd-modelo-bayesiano}

\begin{itemize}
\tightlist
\item
  Análise de Sensibilidade à Multicolinearidade (já que temos features
  com correlação elevada) -\textgreater avaliação do impacto
\end{itemize}

\subsection{{[}TBD{]} Desempenho
Preditivo}\label{tbd-desempenho-preditivo}

\begin{itemize}
\tightlist
\item
  Tabela comparativa
\item
  Curvas ROC
\item
  Métricas
\end{itemize}

\subsection{{[}TBD{]} Interpretação dos
Modelos}\label{tbd-interpretauxe7uxe3o-dos-modelos}

\begin{itemize}
\tightlist
\item
  Coeficientes frequentistas
\item
  Distribuições posteriores bayesianas
\item
  Comparação de incerteza
\end{itemize}

\section{{[}TBD{]} Discussão}\label{tbd-discussuxe3o}

\begin{itemize}
\tightlist
\item
  Diferenças conceituais observadas
\item
  Robustez dos resultados
\item
  Interpretabilidade
\item
  Incerteza
\item
  Aplicabilidade prática
\end{itemize}

\section{{[}TBD{]} Conclusão}\label{tbd-conclusuxe3o}

\begin{itemize}
\tightlist
\item
  Síntese dos resultados
\item
  Quando usar frequentista vs bayesiano
\item
  Limitações
\end{itemize}

Breve explicação do problema, com principais resultados e propostas
futuras

\section*{Referências}\label{referuxeancias}
\addcontentsline{toc}{section}{Referências}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{0}{1}
\bibitem[\citeproctext]{ref-dataset-loan}
GREWAL, Rohit. \textbf{Loan Approval Dataset}. Disponível em:
\textless{}\url{https://www.kaggle.com/datasets/rohitgrewal/loan-approval-dataset}\textgreater.
Acesso em: 11 mar. 2026.

\bibitem[\citeproctext]{ref-Tukey1977}
TUKEY, John W. \textbf{Exploratory Data Analysis}. Reading, MA:
Addison-Wesley, 1977.

\bibitem[\citeproctext]{ref-IndexYouden}
YOUDEN, W. J.
\href{https://doi.org/10.1002/1097-0142(1950)3:1\%3C32::AID-CNCR2820030106\%3E3.0.CO;2-3}{Index
for Rating Diagnostic Tests}. \textbf{Cancer}, v. 3, n. 1, p. 32--35,
1950.

\end{CSLReferences}




\end{document}
